# Generated by Django 4.2.2 on 2023-07-04 05:24

import django.core.validators
from django.db import migrations, models
from django.core.validators import MinValueValidator, MaxValueValidator



class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_data_mobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='mobileNumber',
            field=models.PositiveIntegerField(validators=[MinValueValidator(1000000000),MaxValueValidator(9999999999),],null=False)
    
        ),
    ]
