# Generated by Django 4.2.2 on 2023-07-13 12:46

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_student_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='id',
            field=models.IntegerField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='mobileNumber',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
